spring:
  ###设置请求上传文件大小
  servlet:
    multipart:
      maxFileSize: "10000MB"
      maxRequestSize: "100000MB"
  profiles:
    active: dev



  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.104.9.61:3306/bigdata?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wtl199201180271
    max-wait: 60000
    max-active: 100
    min-idle: 10
    initial-size: 10


server:
  port: 80
